CREATE TABLE listings (
 id text PRIMARY KEY, data jsonb NOT NULL,
 price_usd_minor bigint, price_kgs_minor bigint, availability text NOT NULL, normalized_text text NOT NULL,
 first_seen double precision NOT NULL, last_seen double precision NOT NULL,
 source text NOT NULL DEFAULT 'mashina.kg', market text NOT NULL DEFAULT 'KG',
 original_currency text NOT NULL DEFAULT '', original_price_minor bigint, fx_expires_at double precision,
 normalized_city text NOT NULL DEFAULT '', normalized_body_type text NOT NULL DEFAULT '', normalized_transmission text NOT NULL DEFAULT '',
 vehicle_year integer, mileage_km integer, auction_status text NOT NULL DEFAULT '', auction_at double precision
);
CREATE INDEX listings_recent ON listings(last_seen DESC, first_seen DESC, id);
CREATE INDEX listings_source ON listings(source, market, last_seen);
CREATE INDEX listings_preferences ON listings(normalized_city, normalized_body_type, normalized_transmission, vehicle_year, mileage_km);
CREATE INDEX listings_auction ON listings(auction_status, auction_at);
CREATE TABLE events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, listing_id text NOT NULL REFERENCES listings(id),
 kind text NOT NULL CONSTRAINT events_kind CHECK (kind IN ('new','price_change')), data jsonb NOT NULL,
 previous_usd_minor bigint, previous_kgs_minor bigint, observed_at double precision NOT NULL,
 previous_original_price_minor bigint, previous_original_currency text NOT NULL DEFAULT ''
);
CREATE SEQUENCE profile_revision_seq AS bigint;
CREATE TABLE profiles (
 user_id bigint PRIMARY KEY, chat_id bigint NOT NULL, currency text NOT NULL CONSTRAINT profiles_currency CHECK(currency IN ('USD','KGS')),
 budget_min_minor bigint NOT NULL, budget_max_minor bigint NOT NULL,
 query text NOT NULL, monitoring boolean NOT NULL, revision bigint NOT NULL, cursor bigint NOT NULL,
 quiet_start_minute integer, quiet_end_minute integer, market text NOT NULL DEFAULT 'KG' CONSTRAINT profiles_market CHECK(market IN ('KG','KR','US','ALL')),
 city text NOT NULL DEFAULT '', budget_scope text NOT NULL DEFAULT 'car' CONSTRAINT profiles_budget_scope CHECK(budget_scope IN ('car','total')),
 body_type text NOT NULL DEFAULT '', year_min integer, mileage_max_km integer, transmission text NOT NULL DEFAULT '',
 use_case text NOT NULL DEFAULT '', allow_import boolean, purchase_by text NOT NULL DEFAULT '',
 CONSTRAINT profiles_budget CHECK(budget_min_minor >= 0 AND budget_max_minor >= budget_min_minor AND budget_max_minor > 0),
 CONSTRAINT profiles_quiet_hours CHECK((quiet_start_minute IS NULL AND quiet_end_minute IS NULL) OR
 (quiet_start_minute IS NOT NULL AND quiet_end_minute IS NOT NULL AND quiet_start_minute BETWEEN 0 AND 1439 AND quiet_end_minute BETWEEN 0 AND 1439 AND quiet_start_minute != quiet_end_minute))
);
CREATE TABLE drafts (user_id bigint PRIMARY KEY, state text NOT NULL, data jsonb NOT NULL);
CREATE TABLE metadata (key text PRIMARY KEY, value text NOT NULL);
