CREATE TABLE owner_vehicles (
  user_id bigint PRIMARY KEY,
  chat_id bigint NOT NULL,
  purpose text NOT NULL,
  make_model text NOT NULL,
  year integer NOT NULL,
  mileage_km bigint,
  sale_price_minor bigint,
  sale_currency text,
  property_city text,
  property_type text,
  cash_minor bigint,
  cash_currency text,
  monthly_minor bigint,
  monthly_currency text,
  consent_at double precision NOT NULL,
  updated_at double precision NOT NULL,
  CONSTRAINT owner_purpose CHECK (purpose IN ('sale','property','downpayment')),
  CONSTRAINT owner_vehicle CHECK (length(trim(make_model)) BETWEEN 1 AND 120 AND year BETWEEN 1900 AND 2100 AND (mileage_km IS NULL OR mileage_km BETWEEN 0 AND 10000000)),
  CONSTRAINT owner_sale_money CHECK ((sale_price_minor IS NULL AND sale_currency IS NULL) OR (sale_price_minor IS NOT NULL AND sale_price_minor > 0 AND sale_currency IS NOT NULL AND sale_currency IN ('USD','KGS'))),
  CONSTRAINT owner_cash_money CHECK ((cash_minor IS NULL AND cash_currency IS NULL) OR (cash_minor IS NOT NULL AND cash_minor >= 0 AND cash_currency IS NOT NULL AND cash_currency IN ('USD','KGS'))),
  CONSTRAINT owner_monthly_money CHECK ((monthly_minor IS NULL AND monthly_currency IS NULL) OR (monthly_minor IS NOT NULL AND monthly_minor >= 0 AND monthly_currency IS NOT NULL AND monthly_currency IN ('USD','KGS'))),
  CONSTRAINT owner_property CHECK ((property_city IS NULL OR length(trim(property_city)) BETWEEN 1 AND 80) AND (property_type IS NULL OR property_type IN ('apartment','house','land','commercial','any')) AND (purpose = 'sale' OR (property_city IS NOT NULL AND property_type IS NOT NULL))),
  CONSTRAINT owner_consent CHECK (consent_at > 0 AND updated_at >= consent_at)
);
